### ISSUE TITLE
Reword "Last updated"

### ISSUE THREAD

**Issue by thSoft** [jackfranklin/do-you-even-elm#1]
The "Last updated" message below the most popular and last updated repos seems like it refers to the repo, however it refers to that piece of information. Please reword it (e.g. simply "as of {date}"), and also include the day of month in the date.

**Comment by jackfranklin** [comment]
It does refer to the repository in question, it uses the `updated_at` field from the GitHub API and displays it, so I don't really understand what you mean. If you can clarify though I'm always happy to accept PRs.

**Comment by thSoft** [comment]
I see - then I got confused by the [difference between pushed_at and updated_at](http://stackoverflow.com/questions/15918588/github-api-v3-what-is-the-difference-between-pushed-at-and-updated-at). However, updated_at can also change without a user directly updating a repo. It might be more intuitive to display the value of the pushed_at field?

**Comment by jackfranklin** [comment]
Ah right, yeah that would make sense. Would you like to attempt a PR?
